_BASE_: "Base_OVLVIS_R5021k_4x.yaml"
MODEL:
  WITH_CAPTION: True
  SYNC_CAPTION_BATCH: True
  ROI_BOX_HEAD:
    IMAGE_LOSS_WEIGHT: 0.2
    ADD_IMAGE_BOX: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/cc3m_clip_a+cname.npy'
    DETECTION_WEIGHT_PATH: 'datasets/metadata/lvis_v1_clip_a+cname.npy'
    PROTOTYPE_WEIGHT_PATH: 'exemplar_prototype/coco/coco_ins10_.pth' # 'bbox_prototype/ovcoco_prototype_1x1.pth'
    ATTRIBUTE_VISUAL_WEIGHT_PATH: 'exemplar_prototype/coco/coco_ins100_attribute_kmeans15_.pth'
    CONCEPT_PANDA_COMBINE_WEIGHT: [0.25, 0.0] # 同时使用prototype和attribute特征的加权系数    
    X_NORM_TEMPERATURE: 0.0 # 进行region-region的计算时，对特征x的正则温度
    CONCEPT_SOURCE: 'no' #  'prototype' or 'vg' or 'no'
    CONCEPT_FUSION_MODE: 'no' # 'no' , 'onlyconcept', 'laterfusion', 'earlyfusion'
    IMAGE_LABEL_LOSS: 'concept_grouping'
    ADD_FEATURE_TO_PROP: True
    USE_FED_LOSS: True
    CAT_FREQ_PATH : 'datasets/lvis/lvis_v1_train_norare_cat_info.json'
    CATEGORIES_INFO_PATH: 'datasets/metadata/lvis_ov_categories_info.json'
  WEIGHTS: "models/BoxSup-C2_Lbase_CLIP_R5021k_640b64_4x.pth"
SOLVER:
  MAX_ITER: 90000
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
DATASETS:
  TRAIN: ("lvis_v1_train_norare","cc3m_v1_train_tags")
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetConceptSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [8, 32]
  DATASET_INPUT_SIZE: [800, 400]
  USE_RFS: [True, False]
  DATASET_INPUT_SCALE: [[0.1, 2.0], [0.5, 1.5]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'captiontag']
  NUM_WORKERS: 8
  CONCEPT_GROUP_SIZE: 8
WITH_IMAGE_LABELS: True
SAVE_FEATURES: 'no' # no的话执行训练， 'coco' 或 'lvis'则执行对应的方法，一个是单一尺度，一个是多尺度s